[package]
name = "iouring_cache"
version = "0.1.0"
edition = "2024"

[dependencies]
io-uring = "0.7.10"
libc = "0.2.175"
log = "0.4"
env_logger = "0.11"
httparse = "1.10.1"
glommio = "0.9.0"
futures-lite = "2.6.1"
bytes = "1.10.1"
tokio = { version = "1.47.1", features = ["full"] }
